wordWeb = {
  groups: {
    animals: {
      vertebrates: {
        carnivores: {
          mammals: {
            tiger: {},
            lion: {},
          },
          birds: {
            penguin: {},
          },
          reptiles: {
            snake: {},
          },
          amphibians: {},
          fish: {
            agnatha: {},
            chondrichthyes: {},
            osteichthyes: {
              goldfish: {},
            },
          },
        },
        omnivores: {
          mammals: {
            dog: {},
            pig: {},
            hamster: {},
            monkey: {},
            gorilla: {},
          },
          reptiles: {},
          amphibians: {},
        },
        herbivores: {
          mammals: {
            donkey: {},
            cow: {},
            rabbit: {},
            sheep: {},
            horse: {},
            giraffe: {},
            elephant: {},
          },
          birds: {},
          reptiles: {},
          amphibians: {},
        },
      },
      invertebrates: {
        carnivores: {},
        omnivores: {},
        herbivores: {},
      },
    },
    foods: {
      salad: {},
      sushi: {},
      hamburger: {},
      ice_cream: {},
      cake: {},
      tacos: {},
      fish_and_chips: {},
      meat_pie: {},
      rice: {},
      cereal: {},
      baked_beans: {},
      popcorn: {},
      curry: {},
      lasagne: {},
      spaghetti: {},
      sandwich: {},
      burrito: {},
      ramen_noodles: {},
      soup: {},
      toast: {},
    },
    places: {
      school: {},
      library: {},
      bookstore: {},
      hospital: {},
      zoo: {},
      train_station: {},
      airport: {},
      supermarket: {},
      dentist: {},
      restaurant: {},
      cafe: {},
      swimming_pool: {},
      gym: {},
      bus_station: {},
      vet: {},
      market: {},
      park: {},
      stadium: {},
      bank: {},
      aquarium: {},
    },
    people: {
      Barrack_Obama: {},
      Queen_Elizabeth_II: {},
      Elvis_Presley: {},
      Martin_Scorcese: {},
      Kanye_West: {},
      Beyonce: {},
      Robert_Deniro: {},
      Genghis_Khan: {},
      Ghandi: {},
      Mozart: {},
      J_K_Rowling: {},
      Martin_Luther_King_Jr: {},
      Julius_Ceaser: {},
      Billie_Eilish: {},
      Winston_Churchill: {},
      Rosa_Parks: {},
      Leonardo_da_Vinci: {},
      Beethoven: {},
      Thomas_Edison: {},
      Mark_Twain: {},
    },
    objects: {
      book: {},
      backpack: {},
      pencil_case: {},
      cell_phone: {},
      broom: {},
      pencil: {},
      chair: {},
      sofa: {},
      TV: {},
      speakers: {},
      pillow: {},
      guitar: {},
      calendar: {},
      fan: {},
      kettle: {},
      frying_pan: {},
      vacuum_cleaner: {},
      tennis_racket: {},
      light_bulb: {},
      chopsticks: {},
    },
  },
};

// there are words, then attributes then cates
